Neos:
  Form:
    presets:
      default:
        formElementTypes:
          'Wegmeister.SimpleCaptcha:SimpleCaptcha':
            superTypes:
              'Neos.Form:FormElement': true
              'Neos.Form:TextMixin': true
            implementationClassName: Wegmeister\SimpleCaptcha\FormElements\SimpleCaptcha
            renderingOptions:
              layoutPathPattern: 'resource://{@package}/Private/Form/Layouts/{@type}.html'
              validationErrorTranslationPackage: Wegmeister.SimpleCaptcha
            properties:
              # Time to wait (in seconds) before the formular can be submitted.
              waitTime: 3
              # Maximum time (in seconds) the formular can be sent.
              # After that time, the captcha will be invalid and the user 
              # has to wait for <waitTime> seconds again.
              # Set to 0 to disable the maximum time.
              maxTime: 1800 # 30 minutes
  Neos:
    fusion:
      autoInclude:
        'Wegmeister.SimpleCaptcha': true
    userInterface:
      translation:
        autoInclude:
          'Wegmeister.SimpleCaptcha':
            - 'NodeTypes/*'
